@startuml SimulationTaskStateMachine
title 模拟任务状态机

[*] --> 已创建
note on link
    数据结构:
    id: 主键
    type: 任务类型
    settings: 配置
    status: 状态
    priority: 优先级
    created_at: 创建时间
    scheduled_at: 调度时间
end note

state Active {

    state 已创建 : PENDING
    state 无法调度 : NOT_SCHEDULABLE

    已创建 --> 无法调度 : 停止调度
    已创建 --> 调度器
    note right of 已创建
        提供任务
        1. 数据库
        2. CSV 文件
    end note

    state 调度器 {
        state 未调度
        state 调度
        state scheduler <<choice>>
        scheduler --> 未调度
        scheduler --> 调度
        调度 --> 执行器
        未调度 --> 无法调度
    }


    state 任务评估器 {
        任务评估器 --> 已创建
        note on link
            干预命令
            1. 提高或降低优先级
            2. 停止提供任务，阻止进入调度器
        end note

        任务评估器 --> 调度器
        note on link
            干预命令
            1. 提高或降低优先级
            2. 删除任务，不调度
        end note

        分析: 1. 提高或降低优先级
        分析: 2. 删除任务
    }

    state 执行器 {
        state 执行结束

        已调度 -right-> 运行中 : 启动任务\nRUNNING
        运行中 --> 已完成 : 任务成功\nCOMPLETE
        运行中 --> 已失败 : 任务失败\nFAILED
        已完成 --> 执行结束
        已完成: 生成 Alpha 数据，分析因子信号
        已失败 --> 执行结束
        已失败: 收集错误信息，分析原因
        执行结束 --> 任务评估器
    }

    执行结束 --> [*]
    ' 执行结束 --> 反馈信息 : 反馈任务结果

}



@enduml
