---
config:
  theme: neo-dark
  look: neo
  layout: dagre
  class:
    hideEmptyMembersBox: true
---
classDiagram
direction TB
    class AbstractEvaluateStage {
	    + callback Callable
	    + next AbstractEvaluateStage
	    + init()
	    + do() bool
    }
    class BaseEvaluateStage {
	    + callback Callable
	    + next AbstractEvaluateStage
	    + init()
    }
    class CheckStrategy {
	    + pass_result_set
	    + fail_result_set
	    + default: bool
    }
    class InSampleChecksStage {
	    + default_strategy CheckStrategy
	    + strategies Dict[str, CheckStrategy]
	    + init()
    }
    class CorrelationStage {
	    + threshold
	    + correlation_type
    }
    class ThemeStage {
	    + competition_whitelist
	    + classification_whitelist
	    + theme_whitelist
	    + pyramid_whitelist
	    + competition_whitelist
	    + classification_whitelist
	    + theme_blacklist
	    + pyramid_blacklist
    }
    class SubmissionCheckStage {
    }
    class PerformanceComparisonStage {
    }

	<<Abstract>> AbstractEvaluateStage

    AbstractEvaluateStage <|.. BaseEvaluateStage
    BaseEvaluateStage <-- AbstractEvaluateStage
    BaseEvaluateStage <|-- InSampleChecksStage
    InSampleChecksStage --() strategies
    strategies ()-- CheckStrategy
    BaseEvaluateStage <|-- CorrelationStage
    BaseEvaluateStage <|-- ThemeStage
    BaseEvaluateStage <|-- SubmissionCheckStage
    BaseEvaluateStage <|-- PerformanceComparisonStage
    PerformanceComparisonStage --() performance_comparison_strategy
    performance_comparison_strategy ()-- PerformanceComparisonStrategy
