---
config:
  theme: neo-dark
---
classDiagram
direction TB
    class Researcher {
    }
    class Evaluate {
    }
    class Simulation {
	    + signature
	    + fingerprint
	    + create()
	    + run()
    }
    class Sync {
    }
    class Board {
	    + consultant
	    + genius
	    + competition
    }
    class AlphaEvaluateStages {
	    +AlphaDistribution
	    +SuperAlpha
	    +InSampleGeneralChecks
	    +Theme
	    +Pyramid
	    +Competition
	    +Correlation
	    +RegularOperator
	    +RegularDataFields
	    +ExpressionValidation
    }
    class Alpha {
	    + signature
	    + fingerprint
	    + AggregateData
	    + RecordSets
	    + Distribution
    }
    class Dataset {
	    + DataFields
    }
    class Competition {
    }

    Researcher -- Evaluate
    Researcher -- Simulation
    Researcher -- Sync
    Researcher -- Board
    Evaluate -- AlphaEvaluateStages
    Sync -- Alpha
    Sync -- Dataset
    Sync -- Competition
