---
config:
  theme: neo-dark
  look: neo
  layout: dagre
  class:
    hideEmptyMembersBox: true
---

flowchart TD
    A[数据字段] -->|存储| B(本地数据库)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]